insert into state(id, state) values (1,'California')
insert into state(id, state) values (2,'Pennsylvania')
insert into state(id, state) values (3,'Texas')
insert into state(id, state) values (4,'Colorado')
insert into state(id, state) values (5,'Georgia')
insert into state(id, state) values (6,'North Carolina')
insert into state(id, state) values (7,'Arizona')
insert into state(id, state) values (8,'Alabama')
insert into state(id, state) values (9,'Illinois')
insert into state(id, state) values (10,'Florida')
insert into state(id, state) values (11,'New York')
insert into state(id, state) values (12,'Ohio')

-------------------------------------------------------------------------

insert into location(id, state_id, location) values (1,1,'Los Angeles')
insert into location(id, state_id, location) values (2,1,'San Francisco')
insert into location(id, state_id, location) values (3,1,'San Diego')
insert into location(id, state_id, location) values (4,1,'San Jose')

insert into location(id, state_id, location) values (5,2,'Philadelphia')
insert into location(id, state_id, location) values (6,2,'Pittsburgh')
insert into location(id, state_id, location) values (7,2,'Allentown')
insert into location(id, state_id, location) values (8,2,'Erie')
insert into location(id, state_id, location) values (9,2,'Reading')

insert into location(id, state_id, location) values (10,3,'Houston')
insert into location(id, state_id, location) values (11,3,'San Antonio')
insert into location(id, state_id, location) values (12,3,'Dallas')
insert into location(id, state_id, location) values (13,3,'Austin')
insert into location(id, state_id, location) values (14,3,'El Paso')

insert into location(id, state_id, location) values (15,4,'Denver')
insert into location(id, state_id, location) values (16,4,'Colorado Springs')
insert into location(id, state_id, location) values (17,4,'Aurora')
insert into location(id, state_id, location) values (18,4,'Fort Collins')
insert into location(id, state_id, location) values (19,4,'Lakewood')

insert into location(id, state_id, location) values (20,5,'Atlanta')
insert into location(id, state_id, location) values (21,5,'Columbus')
insert into location(id, state_id, location) values (22,5,'Savannah')
insert into location(id, state_id, location) values (23,5,'Augusta')
insert into location(id, state_id, location) values (24,5,'Macon')

insert into location(id, state_id, location) values (25,6,'Charlotte')
insert into location(id, state_id, location) values (26,6,'Raleigh')
insert into location(id, state_id, location) values (27,6,'Greensboro')
insert into location(id, state_id, location) values (28,6,'Durham')
insert into location(id, state_id, location) values (29,6,'Winston-Salem')

insert into location(id, state_id, location) values (30,7,'Phoenix')
insert into location(id, state_id, location) values (31,7,'Tucson')
insert into location(id, state_id, location) values (32,7,'Mesa')
insert into location(id, state_id, location) values (33,7,'Chandler')
insert into location(id, state_id, location) values (34,7,'Scottsdalen')

insert into location(id, state_id, location) values (35,8,'Huntsville')
insert into location(id, state_id, location) values (36,8,'Birmingham')
insert into location(id, state_id, location) values (37,8,'Montgomery')
insert into location(id, state_id, location) values (38,8,'Mobile')

insert into location(id, state_id, location) values (39,9,'Chicago')
insert into location(id, state_id, location) values (40,9,'Aurora')
insert into location(id, state_id, location) values (41,9,'Naperville')
insert into location(id, state_id, location) values (42,9,'Joliet')
insert into location(id, state_id, location) values (43,9,'Rockford')

insert into location(id, state_id, location) values (44,10,'Jacksonville')
insert into location(id, state_id, location) values (45,10,'Miami')
insert into location(id, state_id, location) values (46,10,'Tampa')
insert into location(id, state_id, location) values (47,10,'Orlando')
insert into location(id, state_id, location) values (48,10,'St. Petersburg')

insert into location(id, state_id, location) values (49,11,'New York City')
insert into location(id, state_id, location) values (50,11,'Buffalo')
insert into location(id, state_id, location) values (51,11,'Rochester')
insert into location(id, state_id, location) values (52,11,'Yonkers')
insert into location(id, state_id, location) values (53,11,'Syracuse')

insert into location(id, state_id, location) values (54,12,'Columbus')
insert into location(id, state_id, location) values (55,12,'Cleveland')
insert into location(id, state_id, location) values (56,12,'Cincinnati')
insert into location(id, state_id, location) values (57,12,'Toledo')
insert into location(id, state_id, location) values (58,12,'Akron')